#include<fltKernel.h>
#include "GlobalVarible.h"

#define DEVICE_OBJECT_NAME      L"\\Device\\ActiveDefence"
#define DEVICE_LINK_NAME        L"\\DosDevices\\ActiveDefence"

#define IOCTL_GET_EVENT_DATA			CTL_CODE(FILE_DEVICE_UNKNOWN, 0xa01, METHOD_BUFFERED, FILE_READ_DATA )
#define IOCTL_GIVE_JUDGMENT_DATA		CTL_CODE(FILE_DEVICE_UNKNOWN, 0xa02, METHOD_BUFFERED, FILE_READ_DATA )
#define IOCTL_GET_MAJOR_INFORMATION		CTL_CODE(FILE_DEVICE_UNKNOWN, 0xa03, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_SET_MAJOR_INFORMATION		CTL_CODE(FILE_DEVICE_UNKNOWN, 0xa04, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

typedef struct _MAJOR_INFORMATION_ {
	ULONG			CrimeType;
	ULONG			IsProtected;
}MAJOR_INFORMATION, * PMAJOR_INFORMATION, * PPMAJOR_INFORMATION;


NTSTATUS		DriverEntry(IN PDRIVER_OBJECT DriObj, IN UNICODE_STRING RegPath);
VOID			DriverUnload(IN PDRIVER_OBJECT DriObj);
NTSTATUS		IoPassThroughDispatch(IN PDEVICE_OBJECT DevObj, IN PIRP irp);
NTSTATUS		IoCreateDispatch(IN PDEVICE_OBJECT DevObj, IN PIRP irp);
NTSTATUS		IoCloseDispatch(IN PDEVICE_OBJECT DevObj, IN PIRP irp);
NTSTATUS		IoDeviceControlDispatch(IN PDEVICE_OBJECT DevObj, IN PIRP irp);
BOOLEAN			DriverEntryInit();
